### PR TITLE
Complete refactor: notes as follows

### PR DESCRIPTION
**Pull request by StewartThomson**
- The update endpoint no longer points to an actualy download link, just the clone hero main page
- Instead I've changed the functionality to crawl the download page and look for the appropriate download link & download it from there. Kind of brute forcey but it works
- Folder/file names are set once in the establishFileName function, easier for page crawling & file moving.
- Mega no longer used (though could be an option because it's still on the download page)
- Some error formatting (for debugging curiosity)

One issue persists: The unarr library returns "unarr: Error Read" for some reason or another, that I can't seem to figure out. Maybe the clonehero site is sending weirdly zipped files? I'm at a loss. Modifying the library to not panic seems to fix the issue and the game runs fine, but that's hard a solution lol.

### CODE REVIEW

**Comment by StewartThomson** [comment]
@JoshuaDoes Let me know what you think, and any possible solutions to the unarr issue listed above! Hopefully we can get this thing back off the ground

**Comment by JoshuaDoes** [comment]
I am very sorry for my late reply!

Thank you for taking an interest in this project, but part of the reason I haven't paid attention to here is because I've been talking to one of the webdevs to get a versions API endpoint setup to make my life easier before I started working on it again. I highly appreciate your effort in getting this to work again, but I'm afraid I'm closing the pull request for now.

Again, thank you!

**Comment by StewartThomson** [comment]
All good!

Yeah that's definitely the way to go lol, my way was just a workaround. Also shortly after making my changes I found out that Clone Hero wasn't even supposed to be getting any future updates (until the surprise release of V.21.7), so it was kind of pointless anyway

**Comment by JoshuaDoes** [comment]
It's all good! The versions API endpoint is setup and ready to go, I've just gotta get around to implementing it now.

**Pull request closed without merging**
